services:
  crmp.contract.repository:
    class: Crmp\AcquisitionBundle\CoreDomain\Contract\ContractRepository
    arguments:
      - '@crmp_acquisition.doctrine.contract_repository'
      - '@doctrine.orm.entity_manager'

  crmp.inquiry.repository:
    class: Crmp\AcquisitionBundle\CoreDomain\Inquiry\InquiryRepository
    arguments:
      - '@crmp_acquisition.doctrine.inquiry_repository'
      - '@doctrine.orm.entity_manager'

  crmp.offer.repository:
    class: Crmp\AcquisitionBundle\CoreDomain\Offer\OfferRepository
    arguments:
      - '@crmp_acquisition.doctrine.offer_repository'
      - '@doctrine.orm.entity_manager'
