services:
  crmp_acquisition.contract.related_panel:
    class: Crmp\CrmBundle\Twig\PanelGroup
    tags:
      - { name: 'crmp.panel_group', alias: 'contract_related' }

  crmp_acquisition.customer.related_panel.contract:
    class: Crmp\AcquisitionBundle\Panel\Customer\ContractPanel
    arguments:
      - '@crmp.contract.repository'
      - '@crmp.controller.render.parameters'
    tags:
      - {name: 'crmp.panel', target: 'customer_related' }

  crmp_acquisition.customer.related_panel.inquiry:
    class: Crmp\AcquisitionBundle\Panel\Customer\InquiryPanel
    arguments:
      - '@crmp.inquiry.repository'
      - '@crmp.controller.render.parameters'
    tags:
      - {name: 'crmp.panel', target: 'customer_related' }

  crmp_acquisition.customer.related_panel.offer:
    class: Crmp\AcquisitionBundle\Panel\Customer\OfferPanel
    arguments:
      - '@crmp.offer.repository'
      - '@crmp.controller.render.parameters'
    tags:
      - {name: 'crmp.panel', target: 'customer_related' }

  crmp_acquisition.inquiry.related_panel:
    class: Crmp\CrmBundle\Twig\PanelGroup
    tags:
      - { name: 'crmp.panel_group', alias: 'inquiry_related' }

  crmp_acquisition.inquiry.related_panel.offer:
    class: Crmp\AcquisitionBundle\Panel\Inquiry\OfferPanel
    arguments:
      - '@crmp.offer.repository'
      - '@crmp.controller.render.parameters'
    tags:
      - {name: 'crmp.panel', target: 'inquiry_related' }

  crmp_acquisition.offer.dashboard_panel:
    class: Crmp\AcquisitionBundle\Panel\Dashboard\OfferPanel
    arguments:
      - '@crmp.offer.repository'
      - '@crmp.controller.render.parameters'
    tags:
      - { name: 'crmp.panel', target: 'dashboard' }

  crmp_acquisition.offer.related_panel:
    class: Crmp\CrmBundle\Twig\PanelGroup
    tags:
      - { name: 'crmp.panel_group', alias: 'offer_related' }

  crmp_acquisition.offer.related_panel.contract:
    class: Crmp\AcquisitionBundle\Panel\Offer\ContractPanel
    arguments:
     - '@crmp.contract.repository'
     - '@crmp.controller.render.parameters'
    tags:
      - { name: 'crmp.panel', target: 'offer_related' }
