services:
  crmp_acquisition.menu:
    public: false
    class: Crmp\AcquisitionBundle\Menu\MenuDecorator
    decorates: crmp.menu_builder
    arguments:
      - "@crmp_acquisition.menu.inner"
      - "@=service('security.token_storage').getToken().getUser()"
      - "@crmp.controller.render.parameters"

  crmp_acquisition.config:
    class: Crmp\AcquisitionBundle\CoreDomain\Config\ConfigRepositoryDecorator
    arguments: ["@crmp_crm.config"]

  crmp_acquisition.contract.related_panel:
    class: Crmp\CrmBundle\Twig\PanelGroup
    tags:
      - { name: 'crmp.panel_group', alias: 'contract_related' }

  crmp_acquisition.customer.related_panel.contract:
    class: Crmp\AcquisitionBundle\Panel\Customer\ContractPanel
    tags:
      - {name: 'crmp.panel', target: 'customer_related' }

  crmp_acquisition.customer.related_panel.inquiry:
    class: Crmp\AcquisitionBundle\Panel\Customer\InquiryPanel
    tags:
      - {name: 'crmp.panel', target: 'customer_related' }

  crmp_acquisition.customer.related_panel.offer:
    class: Crmp\AcquisitionBundle\Panel\Customer\OfferPanel
    tags:
      - {name: 'crmp.panel', target: 'customer_related' }

  crmp_acquisition.doctrine.contract_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - Crmp\AcquisitionBundle\Entity\Contract

  # especially injected in "crmp.inquiry.repository" service
  crmp_acquisition.doctrine.inquiry_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - Crmp\AcquisitionBundle\Entity\Inquiry

  crmp_acquisition.doctrine.offer_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - Crmp\AcquisitionBundle\Entity\Offer

  crmp_acquisition.inquiry.related_panel:
    class: Crmp\CrmBundle\Twig\PanelGroup
    tags:
      - { name: 'crmp.panel_group', alias: 'inquiry_related' }

  crmp_acquisition.inquiry.related_panel.offer:
    class: Crmp\AcquisitionBundle\Panel\Inquiry\OfferPanel
    arguments:
      - '@crmp.offer.repository'
      - '@crmp.controller.render.parameters'
    tags:
      - {name: 'crmp.panel', target: 'inquiry_related' }

  crmp_acquisition.offer.related_panel:
    class: Crmp\CrmBundle\Twig\PanelGroup
    tags:
      - { name: 'crmp.panel_group', alias: 'offer_related' }

  crmp_acquisition.offer.dashboard_panel:
    class: Crmp\AcquisitionBundle\Panel\Dashboard\OfferPanel
    arguments:
      - '@crmp.offer.repository'
      - '@crmp.controller.render.parameters'
    tags:
      - { name: 'crmp.panel', target: 'dashboard' }

  crmp_acquisition.offer.related_panel.contract:
    class: Crmp\AcquisitionBundle\Panel\Offer\ContractPanel
    arguments:
     - '@crmp.contract.repository'
     - '@crmp.controller.render.parameters'
    tags:
      - { name: 'crmp.panel', target: 'offer_related' }
