services:
#    acquisition.example:
#        class: Crmp\AcquisitionBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    crmp.acquisition.menu.prepare:
        class: Crmp\AcquisitionBundle\Event\MenuSubscriber
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }