services:
  crmp.acquisition.menu:
    public: false
    class: Crmp\AcquisitionBundle\Menu\MenuDecorator
    decorates: app.menu_builder
    arguments: ["@crmp.acquisition.menu.inner", "@service_container"]

  crmp.customer.panel.inquiry:
    class: Crmp\AcquisitionBundle\Panel\Customer\InquiryPanel
    tags:
      - {name: 'crmp.panel', target: 'customer_related' }

  crmp.customer.panel.offer:
      class: Crmp\AcquisitionBundle\Panel\Customer\OfferPanel
      tags:
        - {name: 'crmp.panel', target: 'customer_related' }