services:
  crmp_acquisition.menu:
    public: false
    class: Crmp\AcquisitionBundle\Menu\MenuDecorator
    decorates: crmp.menu_builder
    arguments:
      - "@crmp_acquisition.menu.inner"
      - "@=service('security.token_storage').getToken().getUser()"
      - "@crmp.controller.render.parameters"

  crmp_acquisition.config:
    class: Crmp\AcquisitionBundle\CoreDomain\Config\ConfigRepositoryDecorator
    arguments: ["@crmp_crm.config"]

  crmp_acquisition.doctrine.contract_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - Crmp\AcquisitionBundle\Entity\Contract

  # especially injected in "crmp.inquiry.repository" service
  crmp_acquisition.doctrine.inquiry_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - Crmp\AcquisitionBundle\Entity\Inquiry

  crmp_acquisition.doctrine.offer_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - Crmp\AcquisitionBundle\Entity\Offer