language: php
php:
  - '5.6'
  - '7.0'
  - hhvm

services:
  - mysql

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - mysql -e 'create database crmp;'
  - composer install
  - bin/console doctrine:schema:create --env=test
  - bin/console server:run 127.0.0.1:8000 &

script:
  - bin/test-max.sh