language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

services:
  - mysql

install:
  - composer install
  - bin/console server:run 127.0.0.1:8000 &

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - bin/console doctrine:database:create --env=test
  - bin/console doctrine:schema:create --env=test
  - bin/console doctrine:fixtures:load -n --env=test

script:
  - bin/test-max.sh