language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

services:
  - mysql

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - mysql -e 'create database crmp;'
  - composer install
  - bin/console doctrine:schema:create --env=test
  - bin/console cache:warmup
  - bin/console server:run 127.0.0.1:8000 &
  - bin/populate.sh

script:
  - vendor/bin/phpcs --config-set installed_paths vendor/escapestudios/symfony2-coding-standard
  - vendor/bin/phpcs --standard=phpcs.xml src
  - vendor/bin/phpunit --colors=never --coverage-clover var/phpunit/coverage.xml
  - vendor/bin/behat --no-colors -f progress

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - pretzlaw@gmail.com
    on_success: never
    on_failure: change