crmp_hr:
    resource: "@CrmpHrBundle/Controller/"
    type:     annotation
    prefix:   /tasks/

crmp_accounting:
    resource: "@CrmpAccountingBundle/Controller/"
    type:     annotation
    prefix:   /accounting/

crmp_acquisition:
    resource: "@CrmpAcquisitionBundle/Controller/"
    type:     annotation
    prefix:   /

crmp_crm:
    resource: "@CrmpCrmBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"