app:
  resource: "@AppBundle/Controller/"
  type:     annotation

crmp_accounting:
  resource: "@CrmpAccountingBundle/Resources/config/routing.xml"

crmp_acquisition:
  resource: "@CrmpAcquisitionBundle/Resources/config/routing.xml"

crmp_crm:
  resource: "@CrmpCrmBundle/Resources/config/routing.xml"

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"