# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.twig_extension:
    class: AppBundle\Twig\AppExtension
    public: false
    tags:
        - { name: twig.extension }

  app.menu_builder:
    class: AppBundle\Menu\MenuBuilder
    arguments: ["@knp_menu.factory", "@service_container"]

  app.main_menu:
    class: Knp\Menu\MenuItem
    factory: ["@app.menu_builder", createMainMenu]
    arguments: ["@request_stack"]
    tags:
      - { name: knp_menu.menu, alias: main }

  app.related_menu:
      class: Knp\Menu\MenuItem
      factory: ["@app.menu_builder", createSidebarMenu]
      arguments: ["@request_stack"]
      tags:
        - { name: knp_menu.related_menu, alias: related }