services:
#    crmp_acc.example:
#        class: Crmp\AccountingBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  crmp.accounting.menu:
    public: false
    class: Crmp\AccountingBundle\Menu\MenuDecorator
    decorates: app.menu_builder
    arguments: ["@crmp.accounting.menu.inner", "@service_container"]