services:
#    crmp_acc.example:
#        class: Crmp\AccountingBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  crmp.accounting.event.menu:
    class: Crmp\AccountingBundle\Event\MenuSubscriber
    arguments: ["@service_container"]
    tags:
      - { name: kernel.event_subscriber }