services:
  crmp_accounting.menu:
    public: false
    class: Crmp\AccountingBundle\Menu\MenuDecorator
    decorates: crmp.menu_builder
    arguments:
      - "@crmp_accounting.menu.inner"
      - "@=service('security.token_storage').getToken().getUser()"
      - "@crmp.controller.render.parameters"

