services:
#    crmp_acc.example:
#        class: Crmp\AccountingBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  crmp.accounting.menu:
    public: false
    class: Crmp\AccountingBundle\Menu\MenuDecorator
    decorates: app.menu_builder
    arguments: ["@crmp.accounting.menu.inner", "@service_container"]

  crmp.customer.panel.invoices:
    class: Crmp\AccountingBundle\Panel\Customer\InvoicePanel
    tags:
      - { name: 'crmp.panel', target: 'customer_related' }

  crmp.contract.panel.invoices:
    class: Crmp\AccountingBundle\Panel\Contract\InvoicePanel
    tags:
      - { name: 'crmp.panel', target: 'contract_related' }