doctrine:
  orm:
    mappings:
      CrmpCrmBundle:
        type: xml
        dir: Resources/config/doctrine

services:
  crmp.address.repository:
    class: Crmp\CrmBundle\CoreDomain\Address\AddressRepository
    arguments: ['@crmp_crm.doctrine.address_repository', '@doctrine.orm.entity_manager']

  crmp.customer.repository:
    class: Crmp\CrmBundle\CoreDomain\Customer\CustomerRepository
    arguments:
      - '@crmp_crm.doctrine.customer_repository'
      - '@doctrine.orm.entity_manager'

  crmp.setting.repository:
    class: Crmp\CrmBundle\CoreDomain\Settings\SettingsRepository
    arguments:
      - '@crmp_crm.doctrine.setting_repository'
      - '@doctrine.orm.entity_manager'
