services:
  crmp.controller.render.parameters:
    class: ArrayObject

  crmp.menu_builder:
    class: Crmp\CrmBundle\Menu\MenuBuilder
    arguments: ["@knp_menu.factory", "@service_container"]

  crmp.menu.main:
    class: Knp\Menu\MenuItem
    factory: ["@crmp.menu_builder", createMainMenu]
    arguments: ["@request_stack"]
    tags:
      - { name: knp_menu.menu, alias: main }

  crmp.menu.related:
    class: Knp\Menu\MenuItem
    factory: ["@crmp.menu_builder", createRelatedMenu]
    arguments: ["@request_stack"]
    tags:
      - { name: knp_menu.menu, alias: related }

  crmp.menu.user:
    class: Knp\Menu\MenuItem
    factory: ["@crmp.menu_builder", createUserMenu]
    arguments: ["@request_stack"]
    tags:
      - { name: knp_menu.menu, alias: user }

  crmp_crm.address.related_panel:
    class: Crmp\CrmBundle\Twig\PanelGroup
    tags:
      - { name: 'crmp.panel_group', alias: 'address_related' }

  crmp_crm.config:
    class: Crmp\CrmBundle\CoreDomain\Config\ConfigRepository
    arguments: ['@crmp_crm.doctrine.config_repository']

  crmp_crm.doctrine.address_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - Crmp\CrmBundle\Entity\Address

  crmp_crm.doctrine.config_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - Crmp\CrmBundle\Entity\Config

  crmp_crm.doctrine.customer_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - Crmp\CrmBundle\Entity\Customer

  crmp_crm.doctrine.setting_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - Crmp\CrmBundle\Entity\Setting

  crmp_crm.menu:
    public: false
    class: Crmp\CrmBundle\Menu\MenuDecorator
    decorates: crmp.menu_builder
    arguments: ["@crmp_crm.menu.inner", "@service_container"]

  crmp_crm.menu.user:
    public: false
    class: Crmp\CrmBundle\Menu\UserMenu
    decorates: crmp.menu_builder
    arguments: ["@crmp_crm.menu.user.inner", "@service_container"]

  crmp_crm.twig.panels:
    class: Crmp\CrmBundle\Twig\PanelsRenderer
    tags:
      - {name: 'twig.extension' }

  crmp_crm.twig.price:
    class: Crmp\CrmBundle\Twig\PriceRenderer
    tags:
      - {name: 'twig.extension' }

  crmp_crm.twig.register_globals:
    class: Crmp\CrmBundle\Twig\RegisterGlobals
    arguments: ['@service_container']
    tags:
      - {name: 'twig.extension' }

