services:
  crmp.menu.crm:
    public: false
    class: Crmp\CrmBundle\Menu\MenuDecorator
    decorates: app.menu_builder
    arguments: ["@crmp.menu.crm.inner", "@service_container"]

  crmp.twig.panels:
      class: Crmp\CrmBundle\Twig\PanelsRenderer
      tags:
        - {name: 'twig.extension' }

  crmp_crm.customer.panels:
    class: Crmp\CrmBundle\Twig\PanelGroup
    tags:
      - { name: 'crmp.panel_group', alias: 'customer_related' }

  crmp_crm.address.panels:
      class: Crmp\CrmBundle\Twig\PanelGroup
      tags:
        - { name: 'crmp.panel_group', alias: 'address_related' }

  crmp_crm.customer.panel.address:
    class: Crmp\CrmBundle\Twig\AddressPanel
    tags:
      - {name: 'crmp.panel', target: 'customer_related' }
