services:
#    crm.example:
#        class: Crmp\AcquisitionBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    crmp.menu.prepare:
        class: Crmp\CrmBundle\Event\MenuSubscriber
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }
